### ISSUE TITLE
invalid request, please check your server timestamp or recv_window param. 

### ISSUE THREAD

**Issue by SandroG1977** [wuhewuhe/bybit.net.api#32]
Error second time you try get acount information. First Time I instantiate the class AccountServices, it returns information correctly. 

    public class AccountService
    {
        BybitAccountService accountService = new(apiKey: KeysForTesting.Key, apiSecret: KeysForTesting.Secret, url: BybitConstants.HTTP_TESTNET_URL, debugMode: true);

        public async Task<AccountItemDTO> GetAccountBalance(AccountType accountType, string? coin)
        {

            var balance = await accountService.GetAccountBalance(accountType, coin);

                if (balance == null)
                    return new AccountItemDTO();

                var accountList = JsonConvert.DeserializeObject<AccountListDTO>(JObject.Parse(balance)["result"].ToString());
                var accountItem = accountList?.List?.FirstOrDefault();

                return accountItem;
        }

The second time I try get in formation, the Constant CurrentTimeStamp is not updated with the current timeStamp, and get the error> 

"{\"retCode\":10002,\"retMsg\":\"invalid request, please check your server timestamp or recv_window param. req_timestamp[1707082502162],server_timestamp[1707082494985],recv_window[5000]\",\"result\":{},\"retExtInfo\":{},\"time\":1707082494985}"

**Comment by wuhewuhe** [comment]
this issue fixed on version 1.1.0, please retest and tks to your feedback

**Comment by SandroG1977** [comment]
I was using the last package and got that error. I was doing some research and solve the problem with this line. May be the last version was not compiling because an error in 4 UT that were looking for orders that doesn't exists
