### ISSUE TITLE
GetAssetDepositRecords wrong GET query 

### ISSUE THREAD

**Issue by irjadah-dev** [wuhewuhe/bybit.net.api#35]
![image](https://github.com/wuhewuhe/bybit.net.api/assets/57861649/9e06de70-821c-45eb-908f-be535ceedc26)

Looks like we have a wrong endpoint for GetAssetDepositRecords. Should be = "/v5/asset/deposit/query-record" instead of "/v5/asset/deposit-to-account"

**Comment by wuhewuhe** [comment]
will fix it to next version

**Comment by irjadah-dev** [comment]
@wuhewuhe  When are you planning the next version? Is there a way to release the version as alpha? thanks
